services:
  app:
    image: bloglist-front-dev
    build:
      context: ./bloglist-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-frontend/:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    image: bloglist-backend-dev
    build:
      context: ./bloglist-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-backend/:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-proxy
    depends_on:
      - server
      - app
